version: "3.9"

services:
  db:
    image: postgres:15
    container_name: voting_postgres
    restart: unless-stopped
    ports:
      - "${POSTGRES_PORT}:5432"  
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - voting-network

  app:
    build: .
    container_name: voting_app
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "8080:8080"
    env_file:
      - .env
    networks:
      - voting-network

volumes:
  db-data:

networks:
  voting-network:
