name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test-lint:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: zarinaN555
          POSTGRES_DB: voting_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: zarinaN555
      POSTGRES_DB: voting_db
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
      DB_URL: postgres://postgres:zarinaN555@localhost:5432/voting_db?sslmode=disable
      DB_SSLMODE: disable
      JWT_SECRET: a94bff1449080666fd1fee00420ebb42
      ACCESS_TOKEN_TTL_MINUTES: 15
      REFRESH_TOKEN_TTL_DAYS: 7

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Download dependencies
        run: go mod download

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
